NAVIgator/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.about, name='about'),
    path('accounts/signup/', views.signup, name='signup'),

    path('trips/', views.trip_index, name='trip-index'),
    path('trips/create/', views.TripCreate.as_view(), name='trip-create'),
    path('trips/<int:trip_id>/', views.trip_detail, name='trip-detail'),
    path('trips/<int:pk>/update/', views.TripUpdate.as_view(), name='trip-update'),
    path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trip-delete'),
    path('trips/<int:trip_id>/add-transportation', views.add_transportation, name='add-transportation'),
    path('trips/<int:trip_id>/associate-attraction/<int:attraction_id>/', views.associate_attraction, name='associate-attraction'),
    path('trips/<int:trip_id>/remove-attraction/<int:attraction_id>/', views.remove_attraction, name='remove-attraction'),

    path('transportation/create', views.TransportationCreate.as_view(), name='transportation-create'),
    path('transportation/<int:pk>/update', views.TransportationUpdate.as_view(), name='transportation-update'),
    path('transportation/<int:pk>/delete', views.TransportationDelete.as_view(), name='transportation-delete'),
    
    path('attractions/create', views.AttractionCreate.as_view(), name='attraction-create'),
    path('attractions/<int:pk>/', views.AttractionDetail.as_view(), name='attraction-detail'),
    path('attractions/', views.AttractionList.as_view(), name='attraction-index'),
    path('attractions/<int:pk>/update/', views.AttractionUpdate.as_view(), name='attraction-update'),    
    path('attractions/<int:pk>/delete/', views.AttractionDelete.as_view(), name='attraction-delete'),

    ]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Attraction(models.Model):
    name = models.CharField(max_length=100)
    notes = models.TextField(max_length=350)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('attraction-detail', kwargs={'pk': self.id})

class Trip(models.Model):
    location = models.CharField(max_length=100)
    start_date = models.DateField()
    end_date = models.DateField()
    companion = models.CharField(max_length=100)
    emergency_contact = models.CharField(max_length=100)
    old_transportation = models.CharField(max_length=100)
    lodging = models.CharField(max_length=100)
    old_attractions = models.TextField(max_length=250)
    notes = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    attractions = models.ManyToManyField(Attraction)
    
    def __str__(self):
        return self.location

    def get_absolute_url(self):
        return reverse('trip-detail', kwargs={'trip_id': self.id})
    
class Transportation(models.Model):
    type = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    departure_location = models.CharField(max_length=100)
    destination_location = models.CharField(max_length=100)
    ticket_number = models.CharField(max_length=100)
    notes = models.TextField(max_length=250)
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE)

    def __str__(self):
        return self.type

main_app/forms.py
from django import forms
from .models import Trip, Transportation

#from https://docs.djangoproject.com/en/3.0/topics/class-based-views/generic-editing/#model-forms
class DateForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['location', 'start_date', 'end_date', 'companion', 'emergency_contact', 'lodging', 'notes']
        widgets = {
            'start_date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
            'end_date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

class TransportationForm(forms.ModelForm):
    class Meta:
        model = Transportation
        fields = ['type', 'company', 'departure_location', 'destination_location', 'ticket_number', 'notes']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Trip, Attraction, Transportation
from .forms import DateForm, TransportationForm
from django.db import models
from django.views.generic import ListView, DetailView
from django.urls import reverse
from django.contrib.auth.views import LoginView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


#__________Public Views__________#
class Home(LoginView):
    template_name = 'home.html'

def about(request):
    return render(request, 'about.html')

#__________Authorization__________#

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('trip-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)

#__________Athorized-only Views__________#
@login_required
def trip_index(request):
    trips = Trip.objects.filter(user=request.user)
    return render(request, 'trips/index.html', {'trips': trips})

@login_required
def trip_detail(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    transportation_form = TransportationForm()
    attractions_trip_doesnt_have = Attraction.objects.exclude(id__in = trip.attractions.all().values_list('id'))
    return render(request, 'trips/detail.html', {
        'trip': trip,
        'transportation_form': transportation_form,
        'attractions': attractions_trip_doesnt_have
    })

class TripCreate(LoginRequiredMixin, CreateView):
        model = Trip
        form_class = DateForm
        def form_valid(self, form):
            form.instance.user = self.request.user
            return super().form_valid(form)
        
class TripUpdate(LoginRequiredMixin, UpdateView):
    model = Trip
    form_class = DateForm
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class TripDelete(LoginRequiredMixin, DeleteView):
    model = Trip
    success_url = '/trips/'

@login_required
def add_transportation(request, trip_id):
    form = TransportationForm(request.POST)
    if form.is_valid():
        transportation = form.save(commit=False)
        transportation.trip_id = trip_id
        transportation.save()
    return redirect('trip-detail', trip_id=trip_id)

class TransportationCreate(LoginRequiredMixin, CreateView):
    model = Transportation
    fields = "__all__"
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class TransportationUpdate(LoginRequiredMixin, UpdateView):
    model = Transportation
    fields = ['type', 'company', 'departure_location', 'destination_location','ticket_number','notes']
    def get_success_url(self):
        trip_pk = self.object.trip.pk
        return reverse('trip-detail', kwargs={'trip_id':trip_pk})

class TransportationDelete(LoginRequiredMixin, DeleteView):
    model = Transportation
    def get_success_url(self):
        trip_pk = self.object.trip.pk
        return reverse('trip-detail', kwargs={'trip_id':trip_pk})

class AttractionCreate(LoginRequiredMixin, CreateView):
    model = Attraction
    fields = '__all__'

class AttractionList(LoginRequiredMixin, ListView):
    model = Attraction

class AttractionDetail(LoginRequiredMixin, DetailView):
    model = Attraction

class AttractionUpdate(LoginRequiredMixin, UpdateView):
    model = Attraction
    fields = '__all__'

class AttractionDelete(LoginRequiredMixin, DeleteView):
    model = Attraction
    success_url = '/attractions/'

@login_required
def associate_attraction(request, trip_id, attraction_id):
    Trip.objects.get(id=trip_id).attractions.add(attraction_id)
    return redirect('trip-detail', trip_id=trip_id)

@login_required
def remove_attraction(request, trip_id, attraction_id):
    trip = Trip.objects.get(id=trip_id)
    attraction = Attraction.objects.get(id=attraction_id)
    trip.attractions.remove(attraction)
    return redirect('trip-detail', trip_id=trip.id)

main_app/templates/trips/detail.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/trips/trip-detail.css' %}" />

{% endblock %} 
{% block content %}
<section class="cat-container">
  <div class="cat-details">
  <h1>Destination: {{ trip.location }}</h1>
    <div class="cat-actions">
      <a href="{% url 'trip-update' trip.id %}" class="btn warn">Edit</a>
      <a href="{% url 'trip-delete' trip.id %}" class="btn danger">Delete</a>
    </div>
    <div class="cat-img">
      <img src="{% static 'images/cactus.png' %}" alt="A whimsical origami cactus" />
    </div>
  </div>
  <div class="cat-details">
        {% if trip.date > today %}
        <h2>Your upcoming {{ trip.location }} trip</h2>
        {% elif trip.date == today %}
        <h2>Your current {{ trip.location }} trip</h2>
        {% else %}
        <h2>Your past {{ trip.location }} trip</h2>
        {% endif %}
        <h3>Depart: </h3>
          <p>{{trip.start_date}}</p>
        <h3>Return:  </h3>
          <p>{{trip.end_date}}</p>
        <h3>Companion: </h3>
          <p>{{trip.companion}}</p>
        <h3>Emergency Contact: </h3>
          <p>{{trip.emergency_contact}}</p>
        <h3>Transportation: </h3>
          <p>{{trip.old_transportation}}</p>
        <h3>Lodging: </h3>
          <p>{{trip.lodging}}</p>
        <h3>Attractions: </h3>
          <p>{{trip.old_attractions}}</p>
        <h3>Notes: </h3>
          <p>{{ trip.notes }}</p>
  </div>


</section>

<section class="cat-container">


  <div class="feedings-toy-container">
    <section class="feedings">
      <div class="subsection-title">
      <h2>Scheduled Transportation</h2>
      <img src="{% static 'images/fox.png' %}" alt="A whimsical origami fox" />
      </div>
      {% if trip.transportation_set.all.count %}
      <table>
        <thead>
          <tr>
            <th>Type</th>
            <th>Company</th>
            <th>Departure Location</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for transportation in trip.transportation_set.all %}
            <tr>
              <td>{{transportation.type}}</td>
              <td>{{transportation.company}}</td>
              <td>{{transportation.departure_location}}</td>
              <td>
                <a href="{% url 'transportation-update' transportation.id %}" class='btn warn'>Edit</a>
                <a href="{% url 'transportation-delete' transportation.id %}" class='btn danger'>Delete</a> 
              </td>      
            </tr>
          {% endfor %}
        </tbody>
      </table>
          {% else %}
            <div class="subsection-content">
              <p>⚠️ You haven't scheduled a way to get to {{trip.location}} yet!</p>
            </div>
          {% endif %}
    </section>
  </div> 

  <div class="feedings-toy-container">
  <section class="toys">
    <div class="subsection-title">
      <h2>Attractions</h2>
      <img src="{% static 'images/dragon.png' %}" alt="A whimsical origami dragon" />
    </div>

    <h3>{{ trip.location }}'s attractions</h3>
    <div class="subsection-content">
      {% if trip.attractions.count %} 
        {% for attraction in trip.attractions.all %}
          <div class="toy-container">
            <div class="color-block" style="background-color: {{ toy.color }}"></div>
            <a href="{% url 'attraction-detail' attraction.id %}">
              <p>{{ attraction.name }}</p>
            </a>
              <form action="{% url 'remove-attraction' trip.id attraction.id %}" method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Remove Attraction</button>
  </form>

          </div>
        {% endfor %} 
      {% else %}
        <p class="no-toys">{{trip.location}} doesn't have anything scheduled!</p>
      {% endif %}
    </div>

    <h3>Things you can do on your trip:</h3>
    <div class="subsection-content">
      {% if attractions.count %}
          {% for attraction in attractions %}
            <div class="toy-container">
              <div class="color-block" style="background-color: {{ toy.color }}"></div>
              <p>{{ attraction.name }}</p>
              <form action="{% url 'associate-attraction' trip.id attraction.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Add Attraction</button>
              </form>
            </div>
          {% endfor %}
      {% else %}
          <p class="all-toys">{{trip.location}} already has all the available attractions🥳</p>
      {% endif %}
    </div>
  </section>
  </div> 
</section>
{% endblock %}

main_app/templates/trips/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'css/trips/trip-index.css' %}"
/>
{% endblock %} {% block content %}

<section class="page-header">
  <h1>Trip List</h1>
</section>

<section class="card-container">
  {% for trip in trips %}
  <div class="card">
    <a href="{% url 'trip-detail' trip.id %}">
        <div class="card-content">
        <div class="card-img-container">
          <img src="{% static 'images/cactus.png' %}" 
            alt="A whimsical origami cactus" />
        </div>
        <h2 class="card-title">{{ trip.location }}</h2>
        <p>Your {{ trip.location }} trip</p>
        </div>
    </a>
  </div>
  {% endfor %}
</section>

{% endblock %}